# Generated by Django 4.2.7 on 2025-10-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题")),
                ("answer", models.TextField(verbose_name="回答")),
                (
                    "related_articles",
                    models.JSONField(default=list, verbose_name="相关文章ID列表"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "问答会话",
                "verbose_name_plural": "问答会话",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.PositiveIntegerField(verbose_name="文章ID")),
                ("chunk_text", models.TextField(verbose_name="文本块内容")),
                ("chunk_index", models.PositiveIntegerField(verbose_name="块索引")),
                (
                    "vector_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="向量ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章向量",
                "verbose_name_plural": "文章向量",
                "unique_together": {("article_id", "chunk_index")},
            },
        ),
    ]
